image: conan-cpp:latest

# We need to get the full history so we can automatically generate a version:
variables:
  GIT_DEPTH: "0"

stages:
  - init
  - build_and_upload
  - deploy_tst

init:
  stage: init
  script:
    - echo "VERSION=$(./get-version.sh)" > build.env
  artifacts:
    reports:
      dotenv: build.env

build_and_upload:
  stage: build_and_upload
  script:
    - ./build-image.sh
  only:
    - main

deploy_tst:
  stage: deploy_tst
  environment: tst
  image: ansible:latest
  script:
    - ./deploy-to.sh tst $VERSION
  only:
    - main
