---
- name: Deploy Fibonacci WebUI with Docker
  hosts: all
  tasks:
    - name: Start fibonacci-webui container
      community.docker.docker_container:
        name: fibonacci-webui
        # fibonacci_webui_version should be defined on the cmdline:
        image: registry.local:5000/fibonacci-webui:{{ fibonacci_webui_version }}
        state: started
        restart_policy: unless-stopped
        detach: true
        published_ports:
          - "80:8080"
        env:
          # This is the URL to the webservice from the user's browser, NOT from the webui backend.
          # Yes, this is ugly, but to keep the demo simple we don't have a proper backend for the webui.
          FIBONACCI_API_URL: "http://192.168.8.18:27372"
